use customer_behaviour;
select * from customer_data limit 20;

-- Total Revenue generated by genders
SELECT gender , SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY gender;

-- customer used a discount but still spent more than average purchase amount\
SELECT customer_id , purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer_data);

-- Top 5 products with average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_review_rating
FROM customer_data
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- Compare the average shipping between standard and express shipping
SELECT shipping_type , ROUND(AVG(purchase_amount),2) AS avg_amount
FROM customer_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed cutomer spend ? compare avg spend and total revenue betn subs and non-subs
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS avg_amount,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue,avg_amount DESC;

-- Which 5 products have highest percentage of purchase with discount applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100.0,2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customer into NEW,REturning,LOYAL based on thir total number of previous purchases
-- and show count of each
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer_data
)
SELECT customer_segment,COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most purchased within each category
WITH item_category AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer_data
GROUP BY category,item_purchased
)
SELECT 	item_rank,category,item_purchased,total_orders
FROM item_category
WHERE item_rank <= 3;

-- Are customer who are repeat buyes also likely to subscribe
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY  age_group
ORDER BY total_revenue DESC;